// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkFlowManager.Service.Models;

#nullable disable

namespace WorkFlowManager.Service.Migrations
{
    [DbContext(typeof(WorkFlowManagerContext))]
    partial class WorkFlowManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WorkFlowManager.Service.Models.Flow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationStepId")
                        .HasColumnType("int");

                    b.Property<int>("SourceStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationStepId");

                    b.HasIndex("SourceStepId");

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("WorkFlowManager.Service.Models.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepType")
                        .HasColumnType("int");

                    b.Property<int>("WorkFlowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkFlowId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("WorkFlowManager.Service.Models.WorkFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkFlows");
                });

            modelBuilder.Entity("WorkFlowManager.Service.Models.Flow", b =>
                {
                    b.HasOne("WorkFlowManager.Service.Models.Step", "DestinationStep")
                        .WithMany("Tails")
                        .HasForeignKey("DestinationStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkFlowManager.Service.Models.Step", "SourceStep")
                        .WithMany("Heads")
                        .HasForeignKey("SourceStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationStep");

                    b.Navigation("SourceStep");
                });

            modelBuilder.Entity("WorkFlowManager.Service.Models.Step", b =>
                {
                    b.HasOne("WorkFlowManager.Service.Models.WorkFlow", "WorkFlow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkFlow");
                });

            modelBuilder.Entity("WorkFlowManager.Service.Models.Step", b =>
                {
                    b.Navigation("Heads");

                    b.Navigation("Tails");
                });

            modelBuilder.Entity("WorkFlowManager.Service.Models.WorkFlow", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
